/**
 * line chart
 * drawer
 */

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('5{x,v}3\'../7/q\'5{w}3\'../7/r\'5{s}3\'../7/u\'5 b 3\'../l\'p m o n{t(4){e(!4)N I j(\'j!H J K.(4-M)\');8.d=4;L 9=8.d.y.c;e(9){b.k.c=9.G(b.k.c)}}F(g){6 2=8.d;6 1=2.1;6 f=2.h.A,a=2.h.z;1.B();e(g){1.i(C,0,f,a-E)}D{1.i(0,0,f,a)}',50,50,'|ctx|_chartjs|from|FundChart|import|const|utils|this|_color|_chartHeight|Config|colors|chartjs|if|_chartWidth|lineCtnBool|_chart|rect|Error|line|config|default|Draw|class|export|base|animate|drawDashLine|constructor|drawer|getColorRgb|Animation|each|opts|height|width|beginPath|46|else|22|clearCtn|concat|no|new|canvas|element|let|draw|throw'.split('|'),0,{}))

ctx.fillStyle=Config.background;ctx.fill();ctx.closePath();}
drawDashs(){const ctx=this.chartjs.ctx;const width=this.chartjs._chart.width-13,height=this.chartjs._chart.height;let _unit=(height-30)/4;ctx.lineWidth=0;ctx.strokeStyle=Config.dash.color;ctx.beginPath();for(let i=0;i<5;i++){drawDashLine(ctx,50,i*_unit+5,width,i*_unit+5,Config.dash.length);}
ctx.save();}
setDataset(){const _chartjs=this.chartjs,opts=_chartjs.opts,_data=opts.data,_datas=opts.datas;let minData,maxData;let _min,_range,_setRange=opts.range;if(_setRange){if(_setRange.min===undefined||_setRange.max===undefined){throw new Error('Error! param range need min and max');}
_min=_setRange.min;_range=_setRange.max-_setRange.min;}else{if(_datas){_chartjs.multline=true;each(_datas,item=>{let _min=Math.min.apply(null,item);let _max=Math.max.apply(null,item);minData=minData&&minData<_min?minData:_min;maxData=maxData&&maxData>_max?maxData:_max;});}else{minData=Math.min.apply(null,_data);maxData=Math.max.apply(null,_data);}
_range=(maxData-minData);if(_range>2)_range=Math.ceil(_range/4)*4;else _range=_range*1.2;_min=_range>2?Math.floor(minData):minData;if(_min+_range<maxData)_min=minData;}
this.yaxis={min:_min,max:_min+_range,range:_range,unit:_range/4};this.yRate=(30-_chartjs._chart.height)/this.yaxis.range;this.yBasic=5-this.yaxis.max*this.yRate;let _xlength=_data?_data.length:_datas[0].length;this.xaxis={min:0,max:_xlength-1,range:_xlength,unit:1};this.xRate=(_chartjs._chart.width-65)/(_xlength-1);this.xBasic=50;if(_chartjs.multline){let _datasets=[];each(_datas,item=>{let _dataset=[];for(let i=0,len=item.length;i<len;i++){_dataset.push({x:i*this.xRate+this.xBasic,y:item[i]*this.yRate+this.yBasic,value:item[i]});}
_datasets.push(_dataset);});this.chartjs.datasets=_datasets;}else{let _dataset=[];each(_data,(item,i)=>{_dataset.push({x:i*this.xRate+this.xBasic,y:_data[i]*this.yRate+this.yBasic,value:_data[i]});});this.chartjs.dataset=_dataset;}}
drawTexts(){let ctx=this.chartjs.ctx;let _xaxis=this.chartjs.opts.xaxis;let width=this.chartjs._chart.width;let height=this.chartjs._chart.height;ctx.lineWidth=1;ctx.textAlign='right';ctx.font=`${Config.font.fontSize.y} Arial`;ctx.fillStyle=Config.font.color;ctx.fillText(_xaxis[_xaxis.length-1],width-15,height-10);ctx.textAlign='left';ctx.fillText(_xaxis[0],50,height-10);ctx.font='${Config.font.fontSize.x} Arial';ctx.textAlign='right';ctx.textBaseline='middle';let _yaxis=this.yaxis;for(let i=0;i<5;i++){let _val=_yaxis.min+i*_yaxis.unit;ctx.fillText(this.chartjs.opts.yaxisfunc?this.chartjs.opts.yaxisfunc(_val):_val.toFixed(2),45,this.yRate*_val+this.yBasic);}}
drawLine(process=1){let ctx=this.chartjs.ctx;ctx.lineWidth=1;let ymax=this.chartjs._chart.height-24;const drawLinearGradient=color=>{if(this.chartjs.opts.noGradient)return false;let grad=ctx.createLinearGradient(0,0,0,170);const colorArr=getColorRgb(color);grad.addColorStop(0,`rgba(${colorArr.join(',')}, 0.3)`);grad.addColorStop(0.8,`rgba(${colorArr.join(',')}, 0.1)`);grad.addColorStop(1,`rgba(${colorArr.join(',')}, 0.05)`);ctx.fillStyle=grad;ctx.fill();};if(this.chartjs.multline){let _datasets=this.chartjs.datasets;each(_datasets,(item,index)=>{if(index===0){ctx.beginPath();ctx.lineWidth=0;ctx.strokeStyle=Config.background;ctx.moveTo(50,this.chartjs._chart.height-24);for(let i=0;i<_datasets[0].length;i++){ctx.lineTo(_datasets[index][i].x,ymax*(1-process)+_datasets[index][i].y*process);}
ctx.lineTo(_datasets[0][_datasets[0].length-1].x,ymax);ctx.closePath();drawLinearGradient(Config.line.colors[index]);ctx.stroke();}
ctx.lineWidth=1;ctx.strokeStyle=Config.line.colors[index];ctx.beginPath();ctx.moveTo(_datasets[index][0].x,ymax*(1-process)+_datasets[index][0].y*process);each(_datasets[index],item=>{ctx.lineTo(item.x,ymax*(1-process)+item.y*process);});ctx.stroke();});}else{let _dataset=this.chartjs.dataset;ctx.beginPath();ctx.lineWidth=0;ctx.strokeStyle=Config.background;ctx.moveTo(50,this.chartjs._chart.height-24);for(let i=0,len=_dataset.length;i<len;i++){ctx.lineTo(_dataset[i].x,ymax*(1-process)+_dataset[i].y*process);}
ctx.lineTo(_dataset[_dataset.length-1].x,ymax);ctx.closePath();drawLinearGradient(Config.line.colors[0]);ctx.stroke();ctx.strokeStyle=Config.line.colors[0];ctx.beginPath();ctx.moveTo(_dataset[0].x,ymax*(1-process)+_dataset[0].y*process);each(_dataset,item=>{ctx.lineTo(item.x,ymax*(1-process)+item.y*process);});ctx.stroke();}
ctx.save();}
drawPoint(x,y,color,strokeStyle){let ctx=this.chartjs.ctx;ctx.beginPath();ctx.strokeStyle=strokeStyle||'#fff';ctx.lineWidth=1;ctx.arc(x,y,4,0,Math.PI*2,true);ctx.closePath();ctx.fillStyle=color;ctx.fill();ctx.stroke();}
drawHover(x){this.draw(null,true);let ctx=this.chartjs.ctx;if(x>this.chartjs._chart.width-15||x<50)return false;let _index=Math.round((x-this.xBasic)/this.xRate);let _values=[];let _x;let pointsArr=[];if(this.chartjs.multline){let _datasets=this.chartjs.datasets;each(_datasets,(item,index)=>{if(!this.chartjs.opts.hideHoverPoints){pointsArr.push(()=>{this.drawPoint(item[_index].x,item[_index].y-1,Config.line.colors[index]);});}
_x=item[_index].x;_values.push(item[_index].value);});}else{let _dataset=this.chartjs.dataset;if(!this.chartjs.opts.hideHoverPoints){pointsArr.push(()=>{this.drawPoint(_dataset[_index].x,_dataset[_index].y-1,Config.line.colors[0]);});}
_x=_dataset[_index].x;_values.push(_dataset[_index].value);}
ctx.lineWidth=1;ctx.strokeStyle='#999';ctx.beginPath();ctx.moveTo(_x,6);ctx.lineTo(_x,this.chartjs._chart.height-25);ctx.stroke();if(pointsArr.length)each(pointsArr,draw=>{draw()})
if(this.chartjs.opts.hover)this.chartjs.opts.hover(_index,_values,this.chartjs.opts.xaxis[_index]);ctx.restore();}
setEvents(){let $canvas=this.chartjs.canvas;$canvas.addEventListener('touchstart',e=>{let x=e.touches[0].clientX;this.drawHover(x);},false);$canvas.addEventListener('touchmove',e=>{let x=e.touches[0].clientX;this.drawHover(x);return false;},false);}
draw(databool,noanimatebool){this.clearCtn(!databool);this.drawDashs();if(databool){this.setDataset();this.drawTexts();}
if(noanimatebool||!Config.inBrowser)this.drawLine();else{Animation({timing:'easeInOut',duration:400,onProcess:processrate=>{this.clearCtn(true);this.drawDashs();this.drawLine(processrate);},onAnimationFinish:()=>{console.log('chart finish');}});}}
init(){this.draw(true);if(Config.inBrowser&&!this.chartjs.opts.noHoverEvent)this.setEvents();}}